# This is a basic workflow to help you get started with Actions

name: md-to-html

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: change file
              run: echo "" > test.html

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: test.html
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
