# This is a basic workflow to help you get started with Actions

name: md-to-html

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout md
        uses: actions/checkout@v2

      - name: Make HTML from Markdown
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: docs

      - run: |
          dir="docs/"; echo "<html><body><h1>Table of contents</h1>" > ${dir}index.html; for entry in `ls ${dir}*.html|grep -v README`; do entry="${entry#${dir}}"; name="${entry%.html}"; echo "<a href=$entry>${name^}</a><br><br>" >> ${dir}index.html; done; echo "</body></html>" >> ${dir}index.html

      - name: Push changes
        uses: jasineri/simple-push-action@v1
        with:
          file_pattern: docs/*.html
